@api_HostAddress = http://localhost:5074

GET {{api_HostAddress}}/api/users
Accept: application/json

###

POST {{api_HostAddress}}/api/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "cpf": "61942248350",
  "senha": "123456789"
}

### 

POST {{api_HostAddress}}/api/users/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "role": "U",
  "email": "teste10@gmail.com",
  "nome": "André Hasvowlinks",
  "cpf": "61242278767",
  "senha": "liv@1202"
}