@api_HostAddress = http://localhost:5074

POST {{api_HostAddress}}/api/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "cpf": "61242278267",
  "senha": "liv@1203"
}

### 

POST {{api_HostAddress}}/api/users/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "role": "A",
  "email": "teste1@gmail.com",
  "nome": "Aryel Cordeiro Ramos Gonçalves",
  "cpf": "61942248350",
  "senha": "liv@1202"
}

### 

GET {{api_HostAddress}}/api/users/2 HTTP/1.1
Content-Type: application/json
Accept: application/json

### 

GET {{api_HostAddress}}/api/users/list-all HTTP/1.1
Content-Type: application/json
Accept: application/json

### 

PUT {{api_HostAddress}}/api/users/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "role": "A",
  "email": "testee1@gmail.com",
  "nome": "André Hasvowlinks",
  "cpf": "61942248351",
  "senha": "liv@1202"
}
###

PATCH {{api_HostAddress}}/api/users/delete/2?updatedBy=3 HTTP/1.1
Content-Type: application/json
Accept: application/json

###

GET {{api_HostAddress}}/api/chats/list-all HTTP/1.1
Content-Type: application/json
Accept: application/json

###
GET {{api_HostAddress}}/api/chats/by-name/aryel HTTP/1.1
Content-Type: application/json
Accept: application/json

###
POST {{api_HostAddress}}/api/chats/create HTTP/1.1
Content-Type: application/json
Accept: application/json3

{
  "context": "Fale em inglês",
  "nome": "Chat de teste",
  "modelo": "moonshotai/kimi-k2:free",
  "descricao": "Este é um chat moonshotai/kimi-k2:free",
  "status": "A",
  "user_id": 2,
  "created_by": 2
}
 
###
POST {{api_HostAddress}}/api/chats/send-message/3 HTTP/1.1
Content-Type: application/json
Accept: application/json3

{
  "user_id": 2,
  "prompt_input_text": "diga o meu nome 'Aryel'",
  "tipo": "U",
  "send_by": "P",
  "created_by": 2
}

###
GET {{api_HostAddress}}/api/chats/get-messages/2 HTTP/1.1
Content-Type: application/json
Accept: application/json