services:
  db:
    image: postgres:16
    container_name: chatbots_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - chatbots_pgdata:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d

volumes:
  chatbots_pgdata:
