apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  JWT__SECRETKEY: "086d707c1ed7bfa1bdb00324d8187a7c0f80eb20acf4533ba6caca19acdc2154"
  OPENAI_API_KEY: "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"
